# Local Docker Deploy
services:
  # mongo container
  mongo:
    image: mongo:4
    container_name: mongodb_local
    env_file: ../backend/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  # website container
  website:
    image: tahash
    container_name: website_local
    env_file: ../backend/.env
    ports:
      - "3000:3000"
    volumes:
      - website-data:/app/data
    environment:  # Environment variables
      - NODE_ENV=production
      - MONGO_URL=mongodb://localhost:27017/
    depends_on:
        - mongo

volumes:
  mongo-data:
  website-data:
