services:
  # mongo container
  mongo:
    image: mongo
    container_name: mongodb
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
    restart: always

  # website container
  website:
    image: omroux/tahash
    container_name: website
    ports:
      - "3001:3000"
    volumes:
      - website-data:/app/data
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
  website-data:
