# Local Docker Deploy
services:
  # mongo container
  mongo:
    image: mongo
    container_name: mongodb
    env_file: .env
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
    restart: always

  # website container
  website:
    image: tahash
    container_name: website
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - website-data:/app/data
    environment:  # Environment variables
      - NODE_ENV=production
      - MONGO_SERVICE=mongodb
    depends_on:
        - mongo

volumes:
  mongo-data:
    driver: local
  website-data:
