version: '3.8'

services:
  frontend:
    image: omroux/tahash
    env_file: .env
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
  mongo:
    image: mongo
    container_name: mongo
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
    env_file: .env
    restart: always

volumes:
  mongo-data:
    driver: local
