name: Push Docker image to Docker Hub and deploy

on:
  push:
    branches:
      - main

jobs:
  push_to_docker_hub:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # clones the github repo into the Github action runner thing
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v3

      # Login to docker hub using docker/login-action@v3, and it'll use the secrets stored in the GitHub repo
      - name: Login to Docker Hub
        id: login_docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Echo Docker Hub Username
        run: echo ${{ secrets.DOCKER_HUB_USER_NAME }}

      - name: Echo GitHub SHA
        run: echo $GITHUB_SHA

      # builds an updated Docker image
      - name: Build Docker image
        id: build_image
        run: |
          docker build "$GITHUB_WORKSPACE/backend" -f "$GITHUB_WORKSPACE/backend/Dockerfile" -t ${{ secrets.DOCKER_HUB_USER_NAME }}/tahash:latest --label dockerfile-path="backend/Dockerfile"

      # push the new image to the Docker Hub as username/tahash:latest
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/tahash:latest

      # Log out from Docker hub
      - name: Logout from Docker Hub
        run: docker logout

      - name: End
        run: echo "Docker image pushed to Docker Hub successfully"

  deploy_to_server:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: push_to_docker_hub
    steps:
      - name: Checkout code (again, if needed for deploy scripts)
        id: checkout_code_deploy
        uses: actions/checkout@v3

      # SSH to the vps and execute:
      # 1. 'compose down' (stop) the running container
      # 2. pull the new image
      # 3. 'compose up' (start) the new image on a container!
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            docker compose -f ${{ secrets.DOCKER_COMPOSE_PATH }} down
            docker pull ${{ secrets.DOCKER_HUB_USER_NAME }}/tahash:latest
            docker compose -f ${{ secrets.DOCKER_COMPOSE_PATH }} up
